using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.Diagnostics.CodeAnalysis;

namespace AssemblerBackend;

public static class OpcodeClass
{
    public struct OpcodeStruct(byte code, byte size, string debug)
    {
        public readonly byte Size = size;
        public readonly byte Code = code;
        public readonly string Debug = debug;
    }

    public static bool GetOpcodeStruct(byte code, [NotNullWhen(true)] out OpcodeStruct? res)
    {
        if (!OpcodeDictionary.TryGetValue(code, out var v))
        {
            res = null;
            return false;
        }

        res = v;
        return true;
    }

    public static readonly ImmutableDictionary<byte, OpcodeStruct> OpcodeDictionary =
        new Dictionary<byte, OpcodeStruct>()
        {
            { 0x00, new OpcodeStruct(code: 0x00, size: 1, debug: "NOP") },
            { 0x01, new OpcodeStruct(code: 0x01, size: 3, debug: "LXI B,0x{0:X4}") },
            { 0x02, new OpcodeStruct(code: 0x02, size: 1, debug: "STAX B") },
            { 0x03, new OpcodeStruct(code: 0x03, size: 1, debug: "INX B") },
            { 0x04, new OpcodeStruct(code: 0x04, size: 1, debug: "INR B") },
            { 0x05, new OpcodeStruct(code: 0x05, size: 1, debug: "DCR B") },
            { 0x06, new OpcodeStruct(code: 0x06, size: 2, debug: "MVI B, 0x{0:X2}") },
            { 0x07, new OpcodeStruct(code: 0x07, size: 1, debug: "RLC") },
            { 0x09, new OpcodeStruct(code: 0x09, size: 1, debug: "DAD B") },
            { 0x0a, new OpcodeStruct(code: 0x0a, size: 1, debug: "LDAX B") },
            { 0x0b, new OpcodeStruct(code: 0x0b, size: 1, debug: "DCX B") },
            { 0x0c, new OpcodeStruct(code: 0x0c, size: 1, debug: "INR C") },
            { 0x0d, new OpcodeStruct(code: 0x0d, size: 1, debug: "DCR C") },
            { 0x0e, new OpcodeStruct(code: 0x0e, size: 2, debug: "MVI C,0x{0:X2}") },
            { 0x0f, new OpcodeStruct(code: 0x0f, size: 1, debug: "RRC") },
            { 0x11, new OpcodeStruct(code: 0x11, size: 3, debug: "LXI D,0x{0:X4}") },
            { 0x12, new OpcodeStruct(code: 0x12, size: 1, debug: "STAX D") },
            { 0x13, new OpcodeStruct(code: 0x13, size: 1, debug: "INX D") },
            { 0x14, new OpcodeStruct(code: 0x14, size: 1, debug: "INR D") },
            { 0x15, new OpcodeStruct(code: 0x15, size: 1, debug: "DCR D") },
            { 0x16, new OpcodeStruct(code: 0x16, size: 2, debug: "MVI D, 0x{0:X2}") },
            { 0x17, new OpcodeStruct(code: 0x17, size: 1, debug: "RAL") },
            { 0x19, new OpcodeStruct(code: 0x19, size: 1, debug: "DAD D") },
            { 0x1a, new OpcodeStruct(code: 0x1a, size: 1, debug: "LDAX D") },
            { 0x1b, new OpcodeStruct(code: 0x1b, size: 1, debug: "DCX D") },
            { 0x1c, new OpcodeStruct(code: 0x1c, size: 1, debug: "INR E") },
            { 0x1d, new OpcodeStruct(code: 0x1d, size: 1, debug: "DCR E") },
            { 0x1e, new OpcodeStruct(code: 0x1e, size: 2, debug: "MVI E,0x{0:X2}") },
            { 0x1f, new OpcodeStruct(code: 0x1f, size: 1, debug: "RAR") },
            { 0x21, new OpcodeStruct(code: 0x21, size: 3, debug: "LXI H,0x{0:X4}") },
            { 0x22, new OpcodeStruct(code: 0x22, size: 3, debug: "SHLD 0x{0:X4}") },
            { 0x23, new OpcodeStruct(code: 0x23, size: 1, debug: "INX H") },
            { 0x24, new OpcodeStruct(code: 0x24, size: 1, debug: "INR H") },
            { 0x25, new OpcodeStruct(code: 0x25, size: 1, debug: "DCR H") },
            { 0x26, new OpcodeStruct(code: 0x26, size: 2, debug: "MVI H,0x{0:X2}") },
            { 0x27, new OpcodeStruct(code: 0x27, size: 1, debug: "DAA") },
            { 0x29, new OpcodeStruct(code: 0x29, size: 1, debug: "DAD H") },
            { 0x2a, new OpcodeStruct(code: 0x2a, size: 3, debug: "LHLD 0x{0:X4}") },
            { 0x2b, new OpcodeStruct(code: 0x2b, size: 1, debug: "DCX H") },
            { 0x2c, new OpcodeStruct(code: 0x2c, size: 1, debug: "INR L") },
            { 0x2d, new OpcodeStruct(code: 0x2d, size: 1, debug: "DCR L") },
            { 0x2e, new OpcodeStruct(code: 0x2e, size: 2, debug: "MVI L, 0x{0:X2}") },
            { 0x2f, new OpcodeStruct(code: 0x2f, size: 1, debug: "CMA") },
            { 0x31, new OpcodeStruct(code: 0x31, size: 3, debug: "LXI SP, 0x{0:X4}") },
            { 0x32, new OpcodeStruct(code: 0x32, size: 3, debug: "STA 0x{0:X4}") },
            { 0x33, new OpcodeStruct(code: 0x33, size: 1, debug: "INX SP") },
            { 0x34, new OpcodeStruct(code: 0x34, size: 1, debug: "INR M") },
            { 0x35, new OpcodeStruct(code: 0x35, size: 1, debug: "DCR M") },
            { 0x36, new OpcodeStruct(code: 0x36, size: 2, debug: "MVI M,0x{0:X2}") },
            { 0x37, new OpcodeStruct(code: 0x37, size: 1, debug: "STC") },
            { 0x39, new OpcodeStruct(code: 0x39, size: 1, debug: "DAD SP") },
            { 0x3a, new OpcodeStruct(code: 0x3a, size: 3, debug: "LDA 0x{0:X4}") },
            { 0x3b, new OpcodeStruct(code: 0x3b, size: 1, debug: "DCX SP") },
            { 0x3c, new OpcodeStruct(code: 0x3c, size: 1, debug: "INR A") },
            { 0x3d, new OpcodeStruct(code: 0x3d, size: 1, debug: "DCR A") },
            { 0x3e, new OpcodeStruct(code: 0x3e, size: 2, debug: "MVI A,0x{0:X2}") },
            { 0x3f, new OpcodeStruct(code: 0x3f, size: 1, debug: "CMC") },
            { 0x40, new OpcodeStruct(code: 0x40, size: 1, debug: "MOV B,B") },
            { 0x41, new OpcodeStruct(code: 0x41, size: 1, debug: "MOV B,C") },
            { 0x42, new OpcodeStruct(code: 0x42, size: 1, debug: "MOV B,D") },
            { 0x43, new OpcodeStruct(code: 0x43, size: 1, debug: "MOV B,E") },
            { 0x44, new OpcodeStruct(code: 0x44, size: 1, debug: "MOV B,H") },
            { 0x45, new OpcodeStruct(code: 0x45, size: 1, debug: "MOV B,L") },
            { 0x46, new OpcodeStruct(code: 0x46, size: 1, debug: "MOV B,M") },
            { 0x47, new OpcodeStruct(code: 0x47, size: 1, debug: "MOV B,A") },
            { 0x48, new OpcodeStruct(code: 0x48, size: 1, debug: "MOV C,B") },
            { 0x49, new OpcodeStruct(code: 0x49, size: 1, debug: "MOV C,C") },
            { 0x4a, new OpcodeStruct(code: 0x4a, size: 1, debug: "MOV C,D") },
            { 0x4b, new OpcodeStruct(code: 0x4b, size: 1, debug: "MOV C,E") },
            { 0x4c, new OpcodeStruct(code: 0x4c, size: 1, debug: "MOV C,H") },
            { 0x4d, new OpcodeStruct(code: 0x4d, size: 1, debug: "MOV C,L") },
            { 0x4e, new OpcodeStruct(code: 0x4e, size: 1, debug: "MOV C,M") },
            { 0x4f, new OpcodeStruct(code: 0x4f, size: 1, debug: "MOV C,A") },
            { 0x50, new OpcodeStruct(code: 0x50, size: 1, debug: "MOV D,B") },
            { 0x51, new OpcodeStruct(code: 0x51, size: 1, debug: "MOV D,C") },
            { 0x52, new OpcodeStruct(code: 0x52, size: 1, debug: "MOV D,D") },
            { 0x53, new OpcodeStruct(code: 0x53, size: 1, debug: "MOV D,E") },
            { 0x54, new OpcodeStruct(code: 0x54, size: 1, debug: "MOV D,H") },
            { 0x55, new OpcodeStruct(code: 0x55, size: 1, debug: "MOV D,L") },
            { 0x56, new OpcodeStruct(code: 0x56, size: 1, debug: "MOV D,M") },
            { 0x57, new OpcodeStruct(code: 0x57, size: 1, debug: "MOV D,A") },
            { 0x58, new OpcodeStruct(code: 0x58, size: 1, debug: "MOV E,B") },
            { 0x59, new OpcodeStruct(code: 0x59, size: 1, debug: "MOV E,C") },
            { 0x5a, new OpcodeStruct(code: 0x5a, size: 1, debug: "MOV E,D") },
            { 0x5b, new OpcodeStruct(code: 0x5b, size: 1, debug: "MOV E,E") },
            { 0x5c, new OpcodeStruct(code: 0x5c, size: 1, debug: "MOV E,H") },
            { 0x5d, new OpcodeStruct(code: 0x5d, size: 1, debug: "MOV E,L") },
            { 0x5e, new OpcodeStruct(code: 0x5e, size: 1, debug: "MOV E,M") },
            { 0x5f, new OpcodeStruct(code: 0x5f, size: 1, debug: "MOV E,A") },
            { 0x60, new OpcodeStruct(code: 0x60, size: 1, debug: "MOV H,B") },
            { 0x61, new OpcodeStruct(code: 0x61, size: 1, debug: "MOV H,C") },
            { 0x62, new OpcodeStruct(code: 0x62, size: 1, debug: "MOV H,D") },
            { 0x63, new OpcodeStruct(code: 0x63, size: 1, debug: "MOV H,E") },
            { 0x64, new OpcodeStruct(code: 0x64, size: 1, debug: "MOV H,H") },
            { 0x65, new OpcodeStruct(code: 0x65, size: 1, debug: "MOV H,L") },
            { 0x66, new OpcodeStruct(code: 0x66, size: 1, debug: "MOV H,M") },
            { 0x67, new OpcodeStruct(code: 0x67, size: 1, debug: "MOV H,A") },
            { 0x68, new OpcodeStruct(code: 0x68, size: 1, debug: "MOV L,B") },
            { 0x69, new OpcodeStruct(code: 0x69, size: 1, debug: "MOV L,C") },
            { 0x6a, new OpcodeStruct(code: 0x6a, size: 1, debug: "MOV L,D") },
            { 0x6b, new OpcodeStruct(code: 0x6b, size: 1, debug: "MOV L,E") },
            { 0x6c, new OpcodeStruct(code: 0x6c, size: 1, debug: "MOV L,H") },
            { 0x6d, new OpcodeStruct(code: 0x6d, size: 1, debug: "MOV L,L") },
            { 0x6e, new OpcodeStruct(code: 0x6e, size: 1, debug: "MOV L,M") },
            { 0x6f, new OpcodeStruct(code: 0x6f, size: 1, debug: "MOV L,A") },
            { 0x70, new OpcodeStruct(code: 0x70, size: 1, debug: "MOV M,B") },
            { 0x71, new OpcodeStruct(code: 0x71, size: 1, debug: "MOV M,C") },
            { 0x72, new OpcodeStruct(code: 0x72, size: 1, debug: "MOV M,D") },
            { 0x73, new OpcodeStruct(code: 0x73, size: 1, debug: "MOV M,E") },
            { 0x74, new OpcodeStruct(code: 0x74, size: 1, debug: "MOV M,H") },
            { 0x75, new OpcodeStruct(code: 0x75, size: 1, debug: "MOV M,L") },
            { 0x76, new OpcodeStruct(code: 0x76, size: 1, debug: "HLT") },
            { 0x77, new OpcodeStruct(code: 0x77, size: 1, debug: "MOV M,A") },
            { 0x78, new OpcodeStruct(code: 0x78, size: 1, debug: "MOV A,B") },
            { 0x79, new OpcodeStruct(code: 0x79, size: 1, debug: "MOV A,C") },
            { 0x7a, new OpcodeStruct(code: 0x7a, size: 1, debug: "MOV A,D") },
            { 0x7b, new OpcodeStruct(code: 0x7b, size: 1, debug: "MOV A,E") },
            { 0x7c, new OpcodeStruct(code: 0x7c, size: 1, debug: "MOV A,H") },
            { 0x7d, new OpcodeStruct(code: 0x7d, size: 1, debug: "MOV A,L") },
            { 0x7e, new OpcodeStruct(code: 0x7e, size: 1, debug: "MOV A,M") },
            { 0x7f, new OpcodeStruct(code: 0x7f, size: 1, debug: "MOV A,A") },
            { 0x80, new OpcodeStruct(code: 0x80, size: 1, debug: "ADD B") },
            { 0x81, new OpcodeStruct(code: 0x81, size: 1, debug: "ADD C") },
            { 0x82, new OpcodeStruct(code: 0x82, size: 1, debug: "ADD D") },
            { 0x83, new OpcodeStruct(code: 0x83, size: 1, debug: "ADD E") },
            { 0x84, new OpcodeStruct(code: 0x84, size: 1, debug: "ADD H") },
            { 0x85, new OpcodeStruct(code: 0x85, size: 1, debug: "ADD L") },
            { 0x86, new OpcodeStruct(code: 0x86, size: 1, debug: "ADD M") },
            { 0x87, new OpcodeStruct(code: 0x87, size: 1, debug: "ADD A") },
            { 0x88, new OpcodeStruct(code: 0x88, size: 1, debug: "ADC B") },
            { 0x89, new OpcodeStruct(code: 0x89, size: 1, debug: "ADC C") },
            { 0x8a, new OpcodeStruct(code: 0x8a, size: 1, debug: "ADC D") },
            { 0x8b, new OpcodeStruct(code: 0x8b, size: 1, debug: "ADC E") },
            { 0x8c, new OpcodeStruct(code: 0x8c, size: 1, debug: "ADC H") },
            { 0x8d, new OpcodeStruct(code: 0x8d, size: 1, debug: "ADC L") },
            { 0x8e, new OpcodeStruct(code: 0x8e, size: 1, debug: "ADC M") },
            { 0x8f, new OpcodeStruct(code: 0x8f, size: 1, debug: "ADC A") },
            { 0x90, new OpcodeStruct(code: 0x90, size: 1, debug: "SUB B") },
            { 0x91, new OpcodeStruct(code: 0x91, size: 1, debug: "SUB C") },
            { 0x92, new OpcodeStruct(code: 0x92, size: 1, debug: "SUB D") },
            { 0x93, new OpcodeStruct(code: 0x93, size: 1, debug: "SUB E") },
            { 0x94, new OpcodeStruct(code: 0x94, size: 1, debug: "SUB H") },
            { 0x95, new OpcodeStruct(code: 0x95, size: 1, debug: "SUB L") },
            { 0x96, new OpcodeStruct(code: 0x96, size: 1, debug: "SUB M") },
            { 0x97, new OpcodeStruct(code: 0x97, size: 1, debug: "SUB A") },
            { 0x98, new OpcodeStruct(code: 0x98, size: 1, debug: "SBB B") },
            { 0x99, new OpcodeStruct(code: 0x99, size: 1, debug: "SBB C") },
            { 0x9a, new OpcodeStruct(code: 0x9a, size: 1, debug: "SBB D") },
            { 0x9b, new OpcodeStruct(code: 0x9b, size: 1, debug: "SBB E") },
            { 0x9c, new OpcodeStruct(code: 0x9c, size: 1, debug: "SBB H") },
            { 0x9d, new OpcodeStruct(code: 0x9d, size: 1, debug: "SBB L") },
            { 0x9e, new OpcodeStruct(code: 0x9e, size: 1, debug: "SBB M") },
            { 0x9f, new OpcodeStruct(code: 0x9f, size: 1, debug: "SBB A") },
            { 0xa0, new OpcodeStruct(code: 0xa0, size: 1, debug: "ANA B") },
            { 0xa1, new OpcodeStruct(code: 0xa1, size: 1, debug: "ANA C") },
            { 0xa2, new OpcodeStruct(code: 0xa2, size: 1, debug: "ANA D") },
            { 0xa3, new OpcodeStruct(code: 0xa3, size: 1, debug: "ANA E") },
            { 0xa4, new OpcodeStruct(code: 0xa4, size: 1, debug: "ANA H") },
            { 0xa5, new OpcodeStruct(code: 0xa5, size: 1, debug: "ANA L") },
            { 0xa6, new OpcodeStruct(code: 0xa6, size: 1, debug: "ANA M") },
            { 0xa7, new OpcodeStruct(code: 0xa7, size: 1, debug: "ANA A") },
            { 0xa8, new OpcodeStruct(code: 0xa8, size: 1, debug: "XRA B") },
            { 0xa9, new OpcodeStruct(code: 0xa9, size: 1, debug: "XRA C") },
            { 0xaa, new OpcodeStruct(code: 0xaa, size: 1, debug: "XRA D") },
            { 0xab, new OpcodeStruct(code: 0xab, size: 1, debug: "XRA E") },
            { 0xac, new OpcodeStruct(code: 0xac, size: 1, debug: "XRA H") },
            { 0xad, new OpcodeStruct(code: 0xad, size: 1, debug: "XRA L") },
            { 0xae, new OpcodeStruct(code: 0xae, size: 1, debug: "XRA M") },
            { 0xaf, new OpcodeStruct(code: 0xaf, size: 1, debug: "XRA A") },
            { 0xb0, new OpcodeStruct(code: 0xb0, size: 1, debug: "ORA B") },
            { 0xb1, new OpcodeStruct(code: 0xb1, size: 1, debug: "ORA C") },
            { 0xb2, new OpcodeStruct(code: 0xb2, size: 1, debug: "ORA D") },
            { 0xb3, new OpcodeStruct(code: 0xb3, size: 1, debug: "ORA E") },
            { 0xb4, new OpcodeStruct(code: 0xb4, size: 1, debug: "ORA H") },
            { 0xb5, new OpcodeStruct(code: 0xb5, size: 1, debug: "ORA L") },
            { 0xb6, new OpcodeStruct(code: 0xb6, size: 1, debug: "ORA M") },
            { 0xb7, new OpcodeStruct(code: 0xb7, size: 1, debug: "ORA A") },
            { 0xb8, new OpcodeStruct(code: 0xb8, size: 1, debug: "CMP B") },
            { 0xb9, new OpcodeStruct(code: 0xb9, size: 1, debug: "CMP C") },
            { 0xba, new OpcodeStruct(code: 0xba, size: 1, debug: "CMP D") },
            { 0xbb, new OpcodeStruct(code: 0xbb, size: 1, debug: "CMP E") },
            { 0xbc, new OpcodeStruct(code: 0xbc, size: 1, debug: "CMP H") },
            { 0xbd, new OpcodeStruct(code: 0xbd, size: 1, debug: "CMP L") },
            { 0xbe, new OpcodeStruct(code: 0xbe, size: 1, debug: "CMP M") },
            { 0xbf, new OpcodeStruct(code: 0xbf, size: 1, debug: "CMP A") },
            { 0xc0, new OpcodeStruct(code: 0xc0, size: 1, debug: "RNZ") },
            { 0xc1, new OpcodeStruct(code: 0xc1, size: 1, debug: "POP B") },
            { 0xc2, new OpcodeStruct(code: 0xc2, size: 3, debug: "JNZ 0x{0:X4}") },
            { 0xc3, new OpcodeStruct(code: 0xc3, size: 3, debug: "JMP 0x{0:X4}") },
            { 0xc4, new OpcodeStruct(code: 0xc4, size: 3, debug: "CNZ 0x{0:X4}") },
            { 0xc5, new OpcodeStruct(code: 0xc5, size: 1, debug: "PUSH B") },
            { 0xc6, new OpcodeStruct(code: 0xc6, size: 2, debug: "ADI 0x{0:X2}") },
            { 0xc7, new OpcodeStruct(code: 0xc7, size: 1, debug: "RST 0") },
            { 0xc8, new OpcodeStruct(code: 0xc8, size: 1, debug: "RZ") },
            { 0xc9, new OpcodeStruct(code: 0xc9, size: 1, debug: "RET") },
            { 0xca, new OpcodeStruct(code: 0xca, size: 3, debug: "JZ 0x{0:X4}") },
            { 0xcc, new OpcodeStruct(code: 0xcc, size: 3, debug: "CZ 0x{0:X4}") },
            { 0xcd, new OpcodeStruct(code: 0xcd, size: 3, debug: "CALL 0x{0:X4}") },
            { 0xce, new OpcodeStruct(code: 0xce, size: 2, debug: "ACI 0x{0:X2}") },
            { 0xcf, new OpcodeStruct(code: 0xcf, size: 1, debug: "RST 1") },
            { 0xd0, new OpcodeStruct(code: 0xd0, size: 1, debug: "RNC") },
            { 0xd1, new OpcodeStruct(code: 0xd1, size: 1, debug: "POP D") },
            { 0xd2, new OpcodeStruct(code: 0xd2, size: 3, debug: "JNC 0x{0:X4}") },
            { 0xd3, new OpcodeStruct(code: 0xd3, size: 2, debug: "OUT 0x{0:X2}") },
            { 0xd4, new OpcodeStruct(code: 0xd4, size: 3, debug: "CNC 0x{0:X4}") },
            { 0xd5, new OpcodeStruct(code: 0xd5, size: 1, debug: "PUSH D") },
            { 0xd6, new OpcodeStruct(code: 0xd6, size: 2, debug: "SUI 0x{0:X2}") },
            { 0xd7, new OpcodeStruct(code: 0xd7, size: 1, debug: "RST 2") },
            { 0xd8, new OpcodeStruct(code: 0xd8, size: 1, debug: "RC") },
            { 0xda, new OpcodeStruct(code: 0xda, size: 3, debug: "JC 0x{0:X4}") },
            { 0xdb, new OpcodeStruct(code: 0xdb, size: 2, debug: "IN 0x{0:X2}") },
            { 0xdc, new OpcodeStruct(code: 0xdc, size: 3, debug: "CC 0x{0:X4}") },
            { 0xde, new OpcodeStruct(code: 0xde, size: 2, debug: "SBI 0x{0:X2}") },
            { 0xdf, new OpcodeStruct(code: 0xdf, size: 1, debug: "RST 3") },
            { 0xe0, new OpcodeStruct(code: 0xe0, size: 1, debug: "RPO") },
            { 0xe1, new OpcodeStruct(code: 0xe1, size: 1, debug: "POP H") },
            { 0xe2, new OpcodeStruct(code: 0xe2, size: 3, debug: "JPO 0x{0:X4}") },
            { 0xe3, new OpcodeStruct(code: 0xe3, size: 1, debug: "XTHL") },
            { 0xe4, new OpcodeStruct(code: 0xe4, size: 3, debug: "CPO 0x{0:X4}") },
            { 0xe5, new OpcodeStruct(code: 0xe5, size: 1, debug: "PUSH H") },
            { 0xe6, new OpcodeStruct(code: 0xe6, size: 2, debug: "ANI 0x{0:X2}") },
            { 0xe7, new OpcodeStruct(code: 0xe7, size: 1, debug: "RST 4") },
            { 0xe8, new OpcodeStruct(code: 0xe8, size: 1, debug: "RPE") },
            { 0xe9, new OpcodeStruct(code: 0xe9, size: 1, debug: "PCHL") },
            { 0xea, new OpcodeStruct(code: 0xea, size: 3, debug: "JPE 0x{0:X4}") },
            { 0xeb, new OpcodeStruct(code: 0xeb, size: 1, debug: "XCHG") },
            { 0xec, new OpcodeStruct(code: 0xec, size: 3, debug: "CPE 0x{0:X4}") },
            { 0xee, new OpcodeStruct(code: 0xee, size: 2, debug: "XRI 0x{0:X2}") },
            { 0xef, new OpcodeStruct(code: 0xef, size: 1, debug: "RST 5") },
            { 0xf0, new OpcodeStruct(code: 0xf0, size: 1, debug: "RP") },
            { 0xf1, new OpcodeStruct(code: 0xf1, size: 1, debug: "POP PSW") },
            { 0xf2, new OpcodeStruct(code: 0xf2, size: 3, debug: "JP 0x{0:X4}") },
            { 0xf3, new OpcodeStruct(code: 0xf3, size: 1, debug: "DI") },
            { 0xf4, new OpcodeStruct(code: 0xf4, size: 3, debug: "CP 0x{0:X4}") },
            { 0xf5, new OpcodeStruct(code: 0xf5, size: 1, debug: "PUSH PSW") },
            { 0xf6, new OpcodeStruct(code: 0xf6, size: 2, debug: "ORI 0x{0:X2}") },
            { 0xf7, new OpcodeStruct(code: 0xf7, size: 1, debug: "RST 6") },
            { 0xf8, new OpcodeStruct(code: 0xf8, size: 1, debug: "RM") },
            { 0xf9, new OpcodeStruct(code: 0xf9, size: 1, debug: "SPHL") },
            { 0xfa, new OpcodeStruct(code: 0xfa, size: 3, debug: "JM 0x{0:X4}") },
            { 0xfb, new OpcodeStruct(code: 0xfb, size: 1, debug: "EI") },
            { 0xfc, new OpcodeStruct(code: 0xfc, size: 3, debug: "CM 0x{0:X4}") },
            { 0xfe, new OpcodeStruct(code: 0xfe, size: 2, debug: "CPI 0x{0:X2}") },
            { 0xff, new OpcodeStruct(code: 0xff, size: 1, debug: "RST 7") },
        }.ToImmutableDictionary();
}